language: node_js
node_js:
- 10
before_script:
- npm install -g gulp-cli gulp@4
script:
- gulp
- npm run coverage
cache:
  directories:
  - node_modules
env:
  global:
    secure: uXL8QeL5C8VC3ftIy4fNtLcULCbRnYt9EbitctRjlL1mJkg0zfmiDcZKBXqP9tkzGz7Vdaq1qDNZOkFh3FZENJuJXbF78TK9a80P0HCNHH3KRhiNi1Ymbbe00LGE7uQQh4muA0MsQ4yP4eR7JtX2TvpuvD20JTYVFegw9EG+uSc+ikqCAe2OLi16j/rohCLAKEqVHb8A+ChWjGd5HvtUgDNmHmxAo0cTAMlGI4zsINECMUZozVfEqES0nWhSAVTNNEdJdZHz1JtABR3xEK7J0N2U7hStNuPprDXWIZJdFjanoZsmD8Ojg8hQ+lmwXqQPC1A8kxNdRaeCtNIWJLai/PRFt1asywgdsjUZi7KqfzU0/rvn6ryuG85wqdwxNBbQ3ZpzqMwWMPA6Cv7vDhxDwtPd8S8A9q0XGFzBKxKSHaScGJG4ULpGIa3Z/cWIK8TPU9+jnolnvHhBjD3t5BUc2UU22Y99RGjCYY7L9BWYOTCt9SSO0tQwyAoHvoQKQclWVd1eJgNn0LM5fKuN2biMlA3jFG23xGosoemwfiBsfhSAhSdWeLKQltpGPtsDZHBBYUYksXj6xQ75NUgUc7DX+Fj5mUpmpZNktLOp+iRvxNrmMgjopsrV8GeGGFKmMlZUToTBtTSyHTgy48tiuS+D+J7Tn8V82ZhhgW690CPgZ/Q=
notifications:
  slack:
    secure: AMq/LWV7z3a4zJgsxEw2e6jN88CIctIjwSPjZ+40r5g1u+xCqOFY484I3Wyf+qq4H7AkeaYP/bwlVKFoCaNezXcIy6EY4n/7jZbTMylbF/+97BQjzxR53kDPKEXAvKeHTft9Y2ZMU35nbjebpQWqTfz9roGic++sbpicjsRwVr424oViyelXlUjjKJI/zX0EzdkrOKmvqUWWQyNZ+4ogin9DmSiz0t7eOXgd7Ahefk4jyl63VrN98IUcpoqb5q69RFykPw6+6LzQjWC63+6eH11y1puhOpFm6C45Z6W/Xi7hVee+PBc3wopH5RYHIJc7hoosib1N3KaHiDrcYpCNZIN2bREegdeAkzBHZW7lcXPpTql+iBBTNdr2mo/waGoPk92wnsEvMvVpl5UbmjJPxowG5uJ7A9F5jFnQ+9Wbl+zwDcYrNCoRepUHzMQpzrWJs4fheM16XPxhwX49KusfA+w4Dpdq9azkBh2p00f4zhuP6nctyaujHy+kUcR6aMHmEM8p6Dq6G/T/u9flVtPhH374UsymkYDHt3ZudXB0UWs80+qSLFXB4pHqiXpzVteRWJSQroqff7f0cMJ/YPyQFEq/07pMuI38uPxV2ZzyPrGtVqYK3i2q81MveqwkHg77ZDa85mWjJMCcHc/KBXSZbnAWK3/fOaqne+XTUloh0mY=
deploy:
- provider: npm
  api_key:
    secure: GKVJYY5b9k3CI3U5X1t7QL12xxzQo5rJhtz8D7pyRMbtmLhVvjwVNAOIcQTfHuiZxDjS96AxWQckISrJ8rBJH9mK+VkLFQ+F7PJGQC6y0b4HIPt0DdrTzPvXxj8AYVQOc/8p0zqD5xwll2u4VN+8YKib+LdkQyuoNKusEWgJ+1G02KKqm2UK3pwD+vpVXysVoJVuS95rRnosDfpfFCCkEPDsv7bIpJrInfDcD5ZUVUIOedilbXdrkTAmi2PcoPEnVf806NNBUhLreR42KKmDi7B1avBQTRzwMm0/zVwjzZSCeOU2aZ0fqbFhicTixdoPKhz/jpfHndB3Gbg1hFSZQBaTsCSGaeM+e/DTiR/kQVw9n2tHg9PtsGcuoAEsx8WtmkyQWJZG7AfJGkpPu//LN8Y2KSAjtP+DLRR4Rrz/yf33OVxBlMFKC93waJsXAKFuJ3VEbX51X2NAnnTTKv5+TNmo1agwJ+dlcgFF5xes3Lyd6/WWEBsmkfPqWfPzQhWML4NCh2yHqtjW01aPDyJ7HMKeRLnJJ45AFBEePKvnYyFYf4RvJSJ+qTPK6BpNR+/3xJz/EtbsjZutgSgvHarWA1j/uk2Mw5cC6CgqFZb70gmw1PzBJJl8PgGcNdTJiVPdNBqI4C0RkwR2Euy/CHmfF4hx75FJ7BGUXMDM6o0Rmpo=
  email:
    secure: WywMSPtXhYdKzUsfpIWLrS8DQHmiJKVlkYPchxNrrzPdZaB2snyWL8/l2QN84pv8fa4v73VwloBMe1E3triDZYD4kDAjx3A4DmHN62Z41t6+m1pK1R2WJCPQrnDo+S5XYYAtwzdEftqxffSprnpzRVDEhFX5xqPXpApUtFJN8+t0JuMXm1HeIKwApMnOXwPmFa97JiQYsFiUrvNvr6HAaWyn3pBPp0f4MbL+egH319wnGm2tyN/fvUsgcuet0+Cd6N0as+q1UE1SMrzwjWmqulkQrdxl56Jy/H77WCAjx0WQ8BmC6WCb68e8ty+AH/1fZbhN3q5EmSLpZ0CaDKxrv5759pJt1J176tzpAkZV+EskM+admKbxKZpi0+bt4oHQ8ZSOrnFgAgDQoCTYtaH6RmIFXLV+45g4LgvBia1EmQzbNLalWOw0/OPDR8WsHMJwNRSaS9rmslQHWb/OnTq7FcNKvsjm+CKi21H3y9Jgd1qLnUxumILvuda0kgz1swxXgbERXFFVYxL45CfLuaDXobhPwDosc8wmTQcOIHz1VbawTfCbaOrLfRgnXni6Zks88D2BvgOQKywTs1oMduAHHma8bt1RwsVbcwBRQngXTTwtSOUzKCPFK/kIx+KPFhQivqzgzVJmrwZb82NwNsw74toBz4xxrfddlCYV7bc6p8o=
  on:
    branch: master
