language: node_js
node_js:
- 10
before_script:
- npm install -g gulp-cli gulp@4
script:
- gulp
- npm run coverage
cache:
  directories:
  - node_modules
env:
  global:
    secure: hsxwbDwltxib+citYBJVLNaSQ5gVUX/dNJ71cONOsD1n5PkLenLOgO7gYRuMs88g2Z6AA0SF2lg8B7FmVKoMKG0r8ePr8UHdfKa+oOUtozr1+eZigL2y6fbTZKgZobqQ/+H+qczIiTTiMfaaWrNl7qZ7tMP3RbnRDdMbPOuy+hpXwQbc3qoltKI2DcAcxiHehgjJpKQpXYsTbvRgn6fYLfPEecR8Y6QCbq6WFhimqB1QLMQVgidycsEgmvGhVDvCifmsZzyzxDU+93vuegAjTVU9NroOTxmAfsZlss7Qa9fkTBdR9F0uirXlbz2JbTC9FIXeOILjSgfZJ+vUh2bhq3EL5nnhFYfK6lVj1mOIDD0UWzfJcouD/ITkpwuszI2sEBZejcrediEes9070Xn/5MJZ37D4vndKKI+8RMOBuGdsWdtLw2ikVDcsyfdGS3C++l9b0GFrmtM/g9IEeSYASO5tHuHW+ZDgGq1Y7pDHG3cpUCHktZn9V1+YfSdYbARrS/HXVj1F5n3wSM9Lh3Ay3J266fRWpKka3C2ChP1Ww9QtQ3OC631YRD7VZZnJOaOXyy5mhsk33wtaz6AQgh26wOn8YdHZzd09VrrNq20xcwEZumneZQDWbGDU4/u98Ss7ItcO46YQGZRl0jiRo9EgxQshGvA7uhFoPQ8m2+OuwK8=
notifications:
  slack:
    secure: XqHLfnZcABcj6YU3hUgKJTJ6Kp6jPx2gepPS7JXiUGopU6RJ5a+se38nGFupE/nnl1jzCU1Q/1xv06giUeZ+0HO2h4/nxgHCCk5c6mc8GJVg+K8VSOwOIYl5BH9u3GzpB9vA42l1oVhpJxj35/NcG/ByGu2OzYuLFtUPrPb6p0Jlry/l6Qy2NlVa1gM3Ijkiqtm9I0ZqCmR8WIxHRQ/HO6j/rvWNEHTt/NxsUgjdJV/xg9r8jW0mxFaSM9GFz2sElG+e7cN7+U1y0+03BNIwnOAGf7WkJe/64CzRVFYjhee59WI0h9d0eCC9c5RYXi3U0n2taD+YAXo6Dlq4ScHIHOAoer53JwSXy6UROgCP/VpALfd2w7fNCwLoo+Xb9JSGD+GTdk8EOT0LRfR0xtoShKmkp6UPHl6dSwPU1eaqhDTr9Ere/812rYoPnOXdkyp7io2SBDmS+3w63dYdCgtS4n8CMwTEJTRNKIWmjigmYhK9GhWOKqrpfzWL44Z9+6BC9+/9PamI1K+50iWoXhs3dCTvfEMI0aLukrOUp6Ss1afWf2wCs3N6yI43KjLJkOm7hMKTLV3XF2xCoYGC5CHQUj28rogEm1xCIqVVNnAJKzvXcNMr960kRkUtQxYcwhKAb80YvGTb06H78ZSCk3+oPU0fBV/4CpvDOu1jLaB8Q8g=
deploy:
- provider: npm
  api_key:
    secure: lWQayEq8aBjEvIhwr8M0APTuHR6kzS6Mq4ayo9zpenODiv1lSolGBUUOsGb60WL0Ts0Z3BdHYhiQRwpWl0kFHmShqz2Ki5EV07pj01LFgakX6aAzviRcxUylrKSD79SLtrGkrS5Q+0+E7HAKPsHe3rjQYYNyaw6yJWAhq29xKIOKjvaZZP921JFp970LMTxrz/Xk2wPA4M/TINn6HYf9tK2JIYhISLzzcZo/tlXsAHRkwsYznEHSQvnz29TzjMD1DV5yoVnI6sZooD9R/xr+fGqus0V+yw2olr/4l80vnUmNHlb0P9ZeQ6p0+fGPnpq63pcIu6FXf3ZQCegF4YiSJ1lnGvEHA5KQHJY0nBH86UmHWtfy56DT4XqS0Exvl0qUOLQGvr3CvjsMZQpkiBBaM+CTDTVG1LFhMuLdkt6yz5alzjfVeRGq783vFdoaLb9EY2ybBfY19WKvs/M1Aw+EryMLeoPFAU158Aj4vEW6e7daj9CCR61ImqGsTZ/ioe8Hme/IXXFYduJaZsAZFVhx+hyOpAst7Iuh+Mah9yrvKgtynnzQIPXWsY0RFLvy/CjKBUrzySQZ1WJP0W44N7gKom1V7JGlheUc/E0YofWFg3dw/v/LpXKVoWOnMC6gsUr9Aeomxpxn1uKO0Y81BIhoh5Ny1+rokoO6Nxmhn1A4VJ4=
  email:
    secure: w0JHvgp7ey9iBp82Va0VsKoV9Z0BStMpbA992ciimjkM6BzNNKgapE0WKctHl7HEaygidaTA55SUGZ4ICl180aNH7SOtRCsIc5OomQfEwLWDakPmqefyIpTmj4gAvGMN1fpI09I59ThzlrHZTp4JqKRm/qO49Hyjg/dpjnZEDz5AILQnmOjqNRTay2RqTh3OgC5OdJrxeBE0ftnjflM2BykoXo+nWEwRquP8yUfoAPN6k1RJfwcPmvXoTz+BlRfvt0n7io9jqYEJ2Ft3IyhVKdlga3nDCyi27z0SSXXjdArDeJmZLGQw34DzXJ6Dy2Lb4zlY9NlDPzKg6AVKiHsV1dP7FcBLg+DYHf2liW07sgSNiO6jwjDVsQigw5JZsZDlyrumikDV29n8hKAELaefigPEgu6HQNU2005t/BIAIeisqo1kUASgF+6qlicb4ljq9TSmSdR30tzdVIDX70aaDhC5wHaGewRKAPAlDZlrVNIkHixmja/HONXtqYB+sr18GBXdY4DeX/i/uhUiCpEuLBC/dRsc7T05pTCHW5S7VIfMIjo88TlqJ7lkWIawxyRxNMt/ZlmcwOky6m/lNQHFK7hf+4RCfXfYsJFII7GUKhZolzrFwCwyzxE1/PgAWv8YlUVMVsPKi2bM+ST7HZMJMnn+gVGp2mnOJIpFnyyZktc=
  on:
    branch: master
